exports.problem = {
  "subject": "phone",
  "columns": [
    {
      "key": "Brand",
      "full_name": "Brand",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["Apple", "Samsung", "Huawei", "LG"]
    }, {
      "key": "Price",
      "full_name": "Price",
      "type": "numeric",
      "is_objective": true,
      "goal": "min",
      "format": "####0.00",
      "range": {
          "low": 0,
          "high": 1500
      }
    }, {
      "key": "Operating System",
      "full_name": "Operating System",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["IOS", "Android"]
    }, {
      "key": "Valoracion usuarios",
      "full_name": "Valoracion usuarios",
      "type": "numeric",
      "is_objective": false,
      "goal": "max"
    }, {
      "key": "Valoracion OCU",
      "full_name": "Valoracion OCU",
      "type": "categorical",
      "is_objective": false,
      "goal": "max",
      "range": [""]
    }, {
      "key": "Procesador",
      "full_name": "Procesador",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["A10 Fusion", "Octa Core", "A9", "Quad core", "A7"]
    }, {
      "key": "#Core",
      "full_name": "#Core",
      "type": "numeric",
      "is_objective": false,
      "goal": "max"
    }, {
      "key": "Memory",
      "full_name": "Memory",
      "type": "numeric",
      "is_objective": false,
      "goal": "max",
      "format": "####0 GB"

    }, {
      "key": "RAM",
      "full_name": "RAM",
      "type": "numeric",
      "is_objective": false,
      "goal": "max",
      "format": "####0 GB"
    }, {
      "key": "Screen Size inches",
      "full_name": "Screen Size inches",
      "type": "numeric",
      "is_objective": false,
      "goal": "max",
      "range": {
          "low": 0,
          "high": 15
      }
      
    }, {
      "key": "Biometric security",
      "full_name": "Biometric security",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["Fingerprint", "NO"]
    }, {
      "key": "Water resistance",
      "full_name": "Water resistance",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["IP68", "IP67", "NO"]
    }, {
      "key": "Battery (mAh)",
      "full_name": "Battery (mAh)",
      "type": "numeric",
      "is_objective": false,
      "goal": "max"
    }, {
      "key": "Duración Batería Espera",
      "full_name": "Duración Batería Espera",
      "type": "numeric",
      "is_objective": false,
      "goal": "max"
    }, {
      "key": "Duración Batería Conversación",
      "full_name": "Duración Batería Conversación",
      "type": "numeric",
      "is_objective": false,
      "goal": "max"
    }, {
      "key": "Peso",
      "full_name": "Peso",
      "type": "numeric",
      "is_objective": false,
      "goal": "max"
    }, {
      "key": "Front Camera (MP)",
      "full_name": "Front Camera (MP)",
      "type": "numeric",
      "is_objective": false,
      "goal": "max"
    }, {
      "key": "Back Camera (MP)",
      "full_name": "Back Camera (MP)",
      "type": "numeric",
      "is_objective": false,
      "goal": "max"
    }, {
      "key": "back cameras",
      "full_name": "back cameras",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["SI", "NO"]
    }, {
      "key": "Resolución Video",
      "full_name": "Resolución Video",
      "type": "categorical",
      "is_objective": false,
      "goal": "max",
      "range": [""]
    }, {
      "key": "Conectividad Alta velocidad",
      "full_name": "Conectividad Alta velocidad",
      "type": "categorical",
      "is_objective": false,
      "goal": "max",
      "range": ["4G"]
    }, {
      "key": "GPS",
      "full_name": "GPS",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["SI", "NO"]
    }, {
      "key": "Sensors",
      "full_name": "Sensors",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["Alto", "Medio", "Bajo"]
    }, {
      "key": "Carga Inalámbrica",
      "full_name": "Carga Inalámbrica",
      "type": "categorical",
      "is_objective": false,
      "goal": "min",
      "range": ["SI", "NO"]
    }
  ],
"options": [
      {
      "key": "1",
        "name": "K4",
        "values": {
            "Brand": "LG",
            "Price": 70,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Quad core",
            "#Core": 4,
            "Memory": 8,
            "RAM": 1,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 4.5,
            "Biometric security": "NO",
            "Water resistance": "NO",
            "Battery (mAh)": 1940,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 0,
            "Peso": 120,
            "Front Camera (MP)": 2,
            "Back Camera (MP)": 5,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Negro",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Bajo",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "2",
        "name": "Y5 II",
        "values": {
            "Brand": "Huawei",
            "Price": 109,
            "Operating System": "Android",
            "Valoracion usuarios": 4,
            "Valoracion OCU": "",
            "Procesador": "Quad core",
            "#Core": 4,
            "Memory": 8,
            "RAM": 1,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5,
            "Biometric security": "NO",
            "Water resistance": "NO",
            "Battery (mAh)": 2200,
            "Duración Batería Espera": 268,
            "Duración Batería Conversación": 11,
            "Peso": 135,
            "Front Camera (MP)": 2,
            "Back Camera (MP)": 8,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Negro Blanco",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Bajo",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "3",
        "name": "K10",
        "values": {
            "Brand": "LG",
            "Price": 115,
            "Operating System": "Android",
            "Valoracion usuarios": 4,
            "Valoracion OCU": "",
            "Procesador": "Quad core",
            "#Core": 4,
            "Memory": 16,
            "RAM": 1.5,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.3,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 2300,
            "Duración Batería Espera": 255,
            "Duración Batería Conversación": 0,
            "Peso": 153,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 13,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Negro",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "4",
        "name": "Galaxy J3",
        "values": {
            "Brand": "Samsung",
            "Price": 122,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Quad core",
            "#Core": 4,
            "Memory": 8,
            "RAM": 1.5,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5,
            "Biometric security": "NO",
            "Water resistance": "NO",
            "Battery (mAh)": 2600,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 13,
            "Peso": 138,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 8,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Dorado Blanco",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "5",
        "name": "Xcover 3 VE",
        "values": {
            "Brand": "Samsung",
            "Price": 146,
            "Operating System": "Android",
            "Valoracion usuarios": 0,
            "Valoracion OCU": "",
            "Procesador": "Quad core",
            "#Core": 4,
            "Memory": 8,
            "RAM": 1.5,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 4.5,
            "Biometric security": "NO",
            "Water resistance": "IP68",
            "Battery (mAh)": 2200,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 13,
            "Peso": 154,
            "Front Camera (MP)": 2,
            "Back Camera (MP)": 5,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Blanco",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "6",
        "name": "Galaxy J5",
        "values": {
            "Brand": "Samsung",
            "Price": 158,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Quad core",
            "#Core": 4,
            "Memory": 16,
            "RAM": 2,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.2,
            "Biometric security": "NO",
            "Water resistance": "NO",
            "Battery (mAh)": 3100,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 21,
            "Peso": 158,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 13,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Dorado Blanco",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "7",
        "name": "P8 Lite",
        "values": {
            "Brand": "Huawei",
            "Price": 185,
            "Operating System": "Android",
            "Valoracion usuarios": 4,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 16,
            "RAM": 2,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5,
            "Biometric security": "NO",
            "Water resistance": "NO",
            "Battery (mAh)": 2200,
            "Duración Batería Espera": 290,
            "Duración Batería Conversación": 20,
            "Peso": 131,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 13,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Negro",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "8",
        "name": "Galaxy J7",
        "values": {
            "Brand": "Samsung",
            "Price": 200,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 16,
            "RAM": 2,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.5,
            "Biometric security": "NO",
            "Water resistance": "NO",
            "Battery (mAh)": 3300,
            "Duración Batería Espera": 354,
            "Duración Batería Conversación": 18,
            "Peso": 166,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 13,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Negro Blanco Dorado",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "9",
        "name": "P9 Lite",
        "values": {
            "Brand": "Huawei",
            "Price": 209,
            "Operating System": "Android",
            "Valoracion usuarios": 4,
            "Valoracion OCU": "",
            "Procesador": "Quad core",
            "#Core": 4,
            "Memory": 16,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.2,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 3000,
            "Duración Batería Espera": 360,
            "Duración Batería Conversación": 31,
            "Peso": 147,
            "Front Camera (MP)": 8,
            "Back Camera (MP)": 13,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Blanco Negro",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "10",
        "name": "Galaxy A5",
        "values": {
            "Brand": "Samsung",
            "Price": 266,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 16,
            "RAM": 2,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.2,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 2900,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 0,
            "Peso": 145,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 13,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Negro Dorado",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "11",
        "name": "X Cam",
        "values": {
            "Brand": "LG",
            "Price": 279,
            "Operating System": "Android",
            "Valoracion usuarios": 0,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 16,
            "RAM": 2,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.2,
            "Biometric security": "NO",
            "Water resistance": "NO",
            "Battery (mAh)": 2520,
            "Duración Batería Espera": 260,
            "Duración Batería Conversación": 6.8,
            "Peso": 133,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 13,
            "back cameras": "SI",
            "Resolución Video": "",
            "Color": "Gris",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "12",
        "name": "Nova Plus",
        "values": {
            "Brand": "Huawei",
            "Price": 329,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 32,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.5,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 3340,
            "Duración Batería Espera": 800,
            "Duración Batería Conversación": 22,
            "Peso": 160,
            "Front Camera (MP)": 8,
            "Back Camera (MP)": 16,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Negro",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "13",
        "name": "iPhone SE 16GB",
        "values": {
            "Brand": "Apple",
            "Price": 360,
            "Operating System": "IOS",
            "Valoracion usuarios": 0,
            "Valoracion OCU": "",
            "Procesador": "A9",
            "#Core": 8,
            "Memory": 16,
            "RAM": 0,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 4,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 1560,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 113,
            "Peso": 0,
            "Front Camera (MP)": 0,
            "Back Camera (MP)": 12,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Plata Oro Rosa Oro Gris Espacial",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "14",
        "name": "P9",
        "values": {
            "Brand": "Huawei",
            "Price": 389,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 32,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.2,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 3600,
            "Duración Batería Espera": 566,
            "Duración Batería Conversación": 33,
            "Peso": 144,
            "Front Camera (MP)": 8,
            "Back Camera (MP)": 12,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Azul",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "15",
        "name": "iPhone SE 64GB",
        "values": {
            "Brand": "Apple",
            "Price": 400,
            "Operating System": "IOS",
            "Valoracion usuarios": 0,
            "Valoracion OCU": "",
            "Procesador": "A9",
            "#Core": 8,
            "Memory": 64,
            "RAM": 0,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 4,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 1560,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 113,
            "Peso": 0,
            "Front Camera (MP)": 0,
            "Back Camera (MP)": 12,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Plata Oro Rosa Oro Gris Espacial",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Medio",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "16",
        "name": "Galaxy S6",
        "values": {
            "Brand": "Samsung",
            "Price": 450,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 32,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.1,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 2550,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 17,
            "Peso": 138,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 16,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Negro Dorado",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "17",
         "name": "Galaxy S7 ",
        "values": {
            "Brand": "Samsung",
            "Price": 532,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 32,
            "RAM": 4,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.1,
            "Biometric security": "Fingerprint",
            "Water resistance": "IP68",
            "Battery (mAh)": 3000,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 22,
            "Peso": 152,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 12,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Blanco Negro Dorado Plata",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "SI"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "18",
        "name": "iPhone 7  32GB",
        "values": {
            "Brand": "Apple",
            "Price": 575,
            "Operating System": "IOS",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "A10 Fusion",
            "#Core": 8,
            "Memory": 32,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 4.7,
            "Biometric security": "Fingerprint",
            "Water resistance": "IP67",
            "Battery (mAh)": 1969,
            "Duración Batería Espera": 240,
            "Duración Batería Conversación": 14,
            "Peso": 138,
            "Front Camera (MP)": 7,
            "Back Camera (MP)": 12,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Plata Oro Rosa Oro Negro Mate",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "19",
        "name": "P9 Plus",
        "values": {
            "Brand": "Huawei",
            "Price": 599,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 64,
            "RAM": 4,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.5,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 3400,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 0,
            "Peso": 162,
            "Front Camera (MP)": 8,
            "Back Camera (MP)": 12,
            "back cameras": "SI",
            "Resolución Video": "",
            "Color": "Negro",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "20",
        "name": "Galaxy S7 Edge",
        "values": {
            "Brand": "Samsung",
            "Price": 607,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 32,
            "RAM": 4,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.5,
            "Biometric security": "Fingerprint",
            "Water resistance": "IP68",
            "Battery (mAh)": 3000,
            "Duración Batería Espera": 0,
            "Duración Batería Conversación": 27,
            "Peso": 157,
            "Front Camera (MP)": 5,
            "Back Camera (MP)": 12,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Blanco Negro Dorado Plata",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "SI"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    },  {
      "key": "21",
        "name": "Mate 9",
        "values": {
            "Brand": "Huawei",
            "Price": 630,
            "Operating System": "Android",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "Octa Core",
            "#Core": 8,
            "Memory": 64,
            "RAM": 4,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.9,
            "Biometric security": "Fingerprint",
            "Water resistance": "NO",
            "Battery (mAh)": 4000,
            "Duración Batería Espera": 600,
            "Duración Batería Conversación": 28,
            "Peso": 190,
            "Front Camera (MP)": 8,
            "Back Camera (MP)": 20,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Space Gray Moonlight silver",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "22",
        "name": "iPhone 7 128GB",
        "values": {
            "Brand": "Apple",
            "Price": 660,
            "Operating System": "IOS",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "A10 Fusion",
            "#Core": 8,
            "Memory": 128,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 4.7,
            "Biometric security": "Fingerprint",
            "Water resistance": "IP67",
            "Battery (mAh)": 1969,
            "Duración Batería Espera": 240,
            "Duración Batería Conversación": 14,
            "Peso": 138,
            "Front Camera (MP)": 7,
            "Back Camera (MP)": 12,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Plata Oro Rosa Oro Negro Mate",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "23",
        "name": "iPhone 7 plus 32GB",
        "values": {
            "Brand": "Apple",
            "Price": 680,
            "Operating System": "IOS",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "A10 Fusion",
            "#Core": 8,
            "Memory": 32,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.5,
            "Biometric security": "Fingerprint",
            "Water resistance": "IP67",
            "Battery (mAh)": 2900,
            "Duración Batería Espera": 384,
            "Duración Batería Conversación": 21,
            "Peso": 188,
            "Front Camera (MP)": 7,
            "Back Camera (MP)": 12,
            "back cameras": "SI",
            "Resolución Video": "",
            "Color": "Plata Oro Rosa Oro Negro Mate",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "24",
        "name": "iPhone 7 256GB",
        "values": {
            "Brand": "Apple",
            "Price": 745,
            "Operating System": "IOS",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "A10 Fusion",
            "#Core": 8,
            "Memory": 256,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 4.7,
            "Biometric security": "Fingerprint",
            "Water resistance": "IP67",
            "Battery (mAh)": 1969,
            "Duración Batería Espera": 240,
            "Duración Batería Conversación": 14,
            "Peso": 138,
            "Front Camera (MP)": 7,
            "Back Camera (MP)": 12,
            "back cameras": "NO",
            "Resolución Video": "",
            "Color": "Plata Oro Rosa Oro Negro Mate",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "25",
        "name": "iPhone 7 plus 128GB",
        "values": {
            "Brand": "Apple",
            "Price": 765,
            "Operating System": "IOS",
            "Valoracion usuarios": 5,
            "Valoracion OCU": "",
            "Procesador": "A10 Fusion",
            "#Core": 8,
            "Memory": 128,
            "RAM": 3,
            "Tamaño Pantalla Normalizado": "",
            "Screen Size inches": 5.5,
            "Biometric security": "Fingerprint",
            "Water resistance": "IP67",
            "Battery (mAh)": 2900,
            "Duración Batería Espera": 384,
            "Duración Batería Conversación": 21,
            "Peso": 188,
            "Front Camera (MP)": 7,
            "Back Camera (MP)": 12,
            "back cameras": "SI",
            "Resolución Video": "",
            "Color": "Plata Oro Rosa Oro Negro Mate",
            "Conectividad Alta velocidad": "4G",
            "GPS": "SI",
            "Sensors": "Alto",
            "Carga Inalámbrica": "NO"
        },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }, {
      "key": "26",
      "name": "iPhone 7 plus 256GB",
      "values": {
      "Brand": "Apple",
      "Price": 850,
      "Operating System": "IOS",
      "Valoracion usuarios": 5,
      "Valoracion OCU": "",
      "Procesador": "A10 Fusion",
      "#Core": 8,
      "Memory": 256,
      "RAM": 3,
      "Tamaño Pantalla Normalizado": "",
      "Screen Size inches": 5.5,
      "Biometric security": "Fingerprint",
      "Water resistance": "IP67",
      "Battery (mAh)": 2900,
      "Duración Batería Espera": 384,
      "Duración Batería Conversación": 21,
      "Peso": 188,
      "Front Camera (MP)": 7,
      "Back Camera (MP)": 12,
      "back cameras": "SI",
      "Resolución Video": "",
      "Color": "Plata Oro Rosa Oro Negro Mate",
      "Conectividad Alta velocidad": "4G",
      "GPS": "SI",
      "Sensors": "Alto",
      "Carga Inalámbrica": "NO"
      },
      "description_html": "<img style='max-height: 100px; max-width: 100px;'  src='http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Samsung_GALAXY_S4_zoom_%28White%29.jpg/800px-Samsung_GALAXY_S4_zoom_%28White%29.jpg'/> <a title='Photo by Samsung Belgium (Flickr: GALAXY S4 zoom (1)) [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons' href='http://commons.wikimedia.org/wiki/File:Samsung_GALAXY_S4_zoom_(White).jpg' target='_blank'> <img style='max-height: 14px; max-width: 14px;'  src='http://mirrors.creativecommons.org/presskit/icons/cc.png'/> </a>"
    }
  ]
}
